---
- name: Install and run GitHub self-hosted runner
  hosts: ec2host
  become: yes
  vars:
    github_owner: 'meher-liatrio'
    github_repo: 'ansible-ec2'
    runner_token: "{{ lookup('env','RUNNER_TOKEN') }}"
    runner_name: 'ansible-runner'
    runner_work_dir: '_work'
    ansible_ssh_private_key_file: "~/.ssh/gh-runner-key.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: 'ec2-user'    

  tasks:
    - name: Update system packages
      dnf:
        update_cache: yes

    - name: Install necessary packages
      dnf:
        name:
          - jq
          - libicu
          

    - name: Download runner package
      get_url:
        url: "https://github.com/actions/runner/releases/download/v2.316.0/actions-runner-linux-x64-2.316.0.tar.gz"
        dest: "/tmp/actions-runner.tar.gz"

    - name: Create runner directory
      file:
        path: "/home/{{ ansible_user }}/actions-runner"
        state: directory
    
    - name: Change permissions of actions-runner directory
      file:
        path: "/home/{{ ansible_user }}/actions-runner"
        mode: '755'
        recurse: yes

    - name: Extract runner package
      unarchive:
        src: "/tmp/actions-runner.tar.gz"
        dest: "/home/{{ ansible_user }}/actions-runner"
        mode: '777'
        remote_src: yes

    - name: Check if runner is already configured
      stat:
        path: "/home/{{ ansible_user }}/actions-runner/.runner"
      register: runner_status

    - name: Configure runner
      become: no
      command: "./config.sh --url https://github.com/{{ github_owner }}/{{ github_repo}} --token {{ runner_token }} --unattended"
      args:
        chdir: "/home/{{ ansible_user }}/actions-runner"
      when: not runner_status.stat.exists

    - name: Run Runner
      become: no
      command: "./run.sh"
      args:
        chdir: "/home/{{ ansible_user }}/actions-runner"
...